export const customRouteResponse = {
  trip: {
    locations: [
      {
        type: 'break',
        lat: 52.626811,
        lon: 13.50357,
        side_of_street: 'right',
        original_index: 0,
      },
      { type: 'break', lat: 52.543372, lon: 13.50357, original_index: 1 },
    ],
    legs: [
      {
        maneuvers: [
          {
            type: 2,
            instruction: 'Bike northeast.',
            verbal_succinct_transition_instruction:
              'Bike northeast. Then Turn right.',
            verbal_pre_transition_instruction:
              'Bike northeast. Then Turn right.',
            verbal_post_transition_instruction: 'Continue for 100 meters.',
            bearing_after: 33,
            time: 24.512,
            length: 0.128,
            cost: 48.902,
            begin_shape_index: 0,
            end_shape_index: 8,
            verbal_multi_cue: true,
            travel_mode: 'bicycle',
            travel_type: 'hybrid',
          },
          {
            type: 10,
            instruction: 'Turn right.',
            verbal_transition_alert_instruction: 'Turn right.',
            verbal_succinct_transition_instruction: 'Turn right.',
            verbal_pre_transition_instruction: 'Turn right.',
            verbal_post_transition_instruction: 'Continue for 100 meters.',
            bearing_before: 21,
            bearing_after: 91,
            time: 22.155,
            length: 0.105,
            cost: 41.949,
            begin_shape_index: 8,
            end_shape_index: 10,
            travel_mode: 'bicycle',
            travel_type: 'hybrid',
          },
          {
            type: 15,
            instruction: 'Turn left.',
            verbal_transition_alert_instruction: 'Turn left.',
            verbal_succinct_transition_instruction: 'Turn left.',
            verbal_pre_transition_instruction: 'Turn left.',
            verbal_post_transition_instruction: 'Continue for 100 meters.',
            bearing_before: 91,
            bearing_after: 36,
            time: 53.74,
            length: 0.106,
            cost: 539.053,
            begin_shape_index: 10,
            end_shape_index: 18,
            travel_mode: 'bicycle',
            travel_type: 'hybrid',
          },
          {
            type: 10,
            instruction: 'Turn right onto Lindenberger Weg.',
            verbal_transition_alert_instruction:
              'Turn right onto Lindenberger Weg.',
            verbal_succinct_transition_instruction: 'Turn right.',
            verbal_pre_transition_instruction:
              'Turn right onto Lindenberger Weg.',
            verbal_post_transition_instruction: 'Continue for 300 meters.',
            street_names: ['Lindenberger Weg'],
            bearing_before: 55,
            bearing_after: 163,
            time: 57.082,
            length: 0.293,
            cost: 118.469,
            begin_shape_index: 18,
            end_shape_index: 43,
            travel_mode: 'bicycle',
            travel_type: 'hybrid',
          },
          {
            type: 15,
            instruction: 'Turn left to stay on Lindenberger Weg.',
            verbal_transition_alert_instruction:
              'Turn left to stay on Lindenberger Weg.',
            verbal_succinct_transition_instruction:
              'Turn left. Then Turn right to stay on Lindenberger Weg.',
            verbal_pre_transition_instruction:
              'Turn left to stay on Lindenberger Weg. Then Turn right to stay on Lindenberger Weg.',
            verbal_post_transition_instruction: 'Continue for 10 meters.',
            street_names: ['Lindenberger Weg'],
            bearing_before: 149,
            bearing_after: 83,
            time: 5.16,
            length: 0.012,
            cost: 18.905,
            begin_shape_index: 43,
            end_shape_index: 47,
            verbal_multi_cue: true,
            travel_mode: 'bicycle',
            travel_type: 'hybrid',
          },
          {
            type: 10,
            instruction: 'Turn right to stay on Lindenberger Weg.',
            verbal_transition_alert_instruction:
              'Turn right to stay on Lindenberger Weg.',
            verbal_succinct_transition_instruction: 'Turn right.',
            verbal_pre_transition_instruction:
              'Turn right to stay on Lindenberger Weg.',
            verbal_post_transition_instruction: 'Continue for 3 kilometers.',
            street_names: ['Lindenberger Weg'],
            bearing_before: 83,
            bearing_after: 140,
            time: 565.71,
            length: 2.939,
            cost: 1049.577,
            begin_shape_index: 47,
            end_shape_index: 138,
            travel_mode: 'bicycle',
            travel_type: 'hybrid',
          },
          {
            type: 10,
            instruction: 'Turn right onto Karl-Marx-Straße.',
            verbal_transition_alert_instruction:
              'Turn right onto Karl-Marx-Straße.',
            verbal_succinct_transition_instruction: 'Turn right.',
            verbal_pre_transition_instruction:
              'Turn right onto Karl-Marx-Straße.',
            verbal_post_transition_instruction: 'Continue for 200 meters.',
            street_names: ['Karl-Marx-Straße'],
            bearing_before: 170,
            bearing_after: 244,
            time: 39.211,
            length: 0.184,
            cost: 112.711,
            begin_shape_index: 138,
            end_shape_index: 152,
            travel_mode: 'bicycle',
            travel_type: 'hybrid',
          },
          {
            type: 15,
            instruction: 'Turn left onto Alte Schulstraße.',
            verbal_transition_alert_instruction:
              'Turn left onto Alte Schulstraße.',
            verbal_succinct_transition_instruction: 'Turn left.',
            verbal_pre_transition_instruction:
              'Turn left onto Alte Schulstraße.',
            verbal_post_transition_instruction: 'Continue for 400 meters.',
            street_names: ['Alte Schulstraße'],
            bearing_before: 248,
            bearing_after: 171,
            time: 73.852,
            length: 0.37,
            cost: 144.458,
            begin_shape_index: 152,
            end_shape_index: 168,
            travel_mode: 'bicycle',
            travel_type: 'hybrid',
          },
          {
            type: 10,
            instruction: 'Turn right to stay on Alte Schulstraße.',
            verbal_transition_alert_instruction:
              'Turn right to stay on Alte Schulstraße.',
            verbal_succinct_transition_instruction:
              'Turn right. Then Turn left onto Wartenberger Straße.',
            verbal_pre_transition_instruction:
              'Turn right to stay on Alte Schulstraße. Then Turn left onto Wartenberger Straße.',
            verbal_post_transition_instruction: 'Continue for 40 meters.',
            street_names: ['Alte Schulstraße'],
            bearing_before: 172,
            bearing_after: 253,
            time: 8.91,
            length: 0.041,
            cost: 16.743,
            begin_shape_index: 168,
            end_shape_index: 171,
            verbal_multi_cue: true,
            travel_mode: 'bicycle',
            travel_type: 'hybrid',
          },
          {
            type: 15,
            instruction: 'Turn left onto Wartenberger Straße.',
            verbal_transition_alert_instruction:
              'Turn left onto Wartenberger Straße.',
            verbal_succinct_transition_instruction: 'Turn left.',
            verbal_pre_transition_instruction:
              'Turn left onto Wartenberger Straße.',
            verbal_post_transition_instruction: 'Continue for 700 meters.',
            street_names: ['Wartenberger Straße'],
            bearing_before: 254,
            bearing_after: 165,
            time: 141.798,
            length: 0.723,
            cost: 253.854,
            begin_shape_index: 171,
            end_shape_index: 198,
            travel_mode: 'bicycle',
            travel_type: 'hybrid',
          },
          {
            type: 9,
            instruction: 'Bear right onto Lindenberger Straße.',
            verbal_transition_alert_instruction:
              'Bear right onto Lindenberger Straße.',
            verbal_succinct_transition_instruction: 'Bear right.',
            verbal_pre_transition_instruction:
              'Bear right onto Lindenberger Straße.',
            verbal_post_transition_instruction: 'Continue for 2 kilometers.',
            street_names: ['Lindenberger Straße'],
            bearing_before: 157,
            bearing_after: 180,
            time: 391.396,
            length: 2.111,
            cost: 695.407,
            begin_shape_index: 198,
            end_shape_index: 242,
            travel_mode: 'bicycle',
            travel_type: 'hybrid',
          },
          {
            type: 15,
            instruction: 'Turn left onto Dorfstraße.',
            verbal_transition_alert_instruction: 'Turn left onto Dorfstraße.',
            verbal_succinct_transition_instruction: 'Turn left.',
            verbal_pre_transition_instruction: 'Turn left onto Dorfstraße.',
            verbal_post_transition_instruction: 'Continue for 800 meters.',
            street_names: ['Dorfstraße'],
            bearing_before: 190,
            bearing_after: 106,
            time: 158.929,
            length: 0.763,
            cost: 392.027,
            begin_shape_index: 242,
            end_shape_index: 290,
            travel_mode: 'bicycle',
            travel_type: 'hybrid',
          },
          {
            type: 10,
            instruction: 'Turn right onto the cycleway.',
            verbal_transition_alert_instruction:
              'Turn right onto the cycleway.',
            verbal_succinct_transition_instruction: 'Turn right.',
            verbal_pre_transition_instruction: 'Turn right onto the cycleway.',
            verbal_post_transition_instruction: 'Continue for 500 meters.',
            bearing_before: 169,
            bearing_after: 253,
            time: 117.172,
            length: 0.466,
            cost: 222.945,
            begin_shape_index: 290,
            end_shape_index: 321,
            travel_mode: 'bicycle',
            travel_type: 'hybrid',
          },
          {
            type: 9,
            instruction: 'Bear right onto Falkenberger Chaussee.',
            verbal_transition_alert_instruction:
              'Bear right onto Falkenberger Chaussee.',
            verbal_succinct_transition_instruction: 'Bear right.',
            verbal_pre_transition_instruction:
              'Bear right onto Falkenberger Chaussee.',
            verbal_post_transition_instruction: 'Continue for 800 meters.',
            street_names: ['Falkenberger Chaussee'],
            bearing_before: 198,
            bearing_after: 238,
            time: 140.678,
            length: 0.772,
            cost: 290.044,
            begin_shape_index: 321,
            end_shape_index: 356,
            travel_mode: 'bicycle',
            travel_type: 'hybrid',
          },
          {
            type: 15,
            instruction: 'Turn left onto Rüdickenstraße.',
            verbal_transition_alert_instruction:
              'Turn left onto Rüdickenstraße.',
            verbal_succinct_transition_instruction: 'Turn left.',
            verbal_pre_transition_instruction: 'Turn left onto Rüdickenstraße.',
            verbal_post_transition_instruction: 'Continue for 200 meters.',
            street_names: ['Rüdickenstraße'],
            bearing_before: 239,
            bearing_after: 144,
            time: 48.024,
            length: 0.191,
            cost: 116.324,
            begin_shape_index: 356,
            end_shape_index: 375,
            travel_mode: 'bicycle',
            travel_type: 'hybrid',
          },
          {
            type: 10,
            instruction: 'Turn right to stay on Rüdickenstraße.',
            verbal_transition_alert_instruction:
              'Turn right to stay on Rüdickenstraße.',
            verbal_succinct_transition_instruction: 'Turn right.',
            verbal_pre_transition_instruction:
              'Turn right to stay on Rüdickenstraße.',
            verbal_post_transition_instruction: 'Continue for 100 meters.',
            street_names: ['Rüdickenstraße'],
            bearing_before: 140,
            bearing_after: 235,
            time: 21.57,
            length: 0.098,
            cost: 40.015,
            begin_shape_index: 375,
            end_shape_index: 379,
            travel_mode: 'bicycle',
            travel_type: 'hybrid',
          },
          {
            type: 15,
            instruction: 'Turn left to stay on Rüdickenstraße.',
            verbal_transition_alert_instruction:
              'Turn left to stay on Rüdickenstraße.',
            verbal_succinct_transition_instruction:
              'Turn left. Then Turn left onto Privatstraße 12.',
            verbal_pre_transition_instruction:
              'Turn left to stay on Rüdickenstraße. Then Turn left onto Privatstraße 12.',
            verbal_post_transition_instruction: 'Continue for 60 meters.',
            street_names: ['Rüdickenstraße'],
            bearing_before: 250,
            bearing_after: 150,
            time: 18.64,
            length: 0.058,
            cost: 72.753,
            begin_shape_index: 379,
            end_shape_index: 389,
            verbal_multi_cue: true,
            travel_mode: 'bicycle',
            travel_type: 'hybrid',
          },
          {
            type: 15,
            instruction: 'Turn left onto Privatstraße 12.',
            verbal_transition_alert_instruction:
              'Turn left onto Privatstraße 12.',
            verbal_succinct_transition_instruction: 'Turn left.',
            verbal_pre_transition_instruction:
              'Turn left onto Privatstraße 12.',
            verbal_post_transition_instruction: 'Continue for 300 meters.',
            street_names: ['Privatstraße 12'],
            bearing_before: 200,
            bearing_after: 114,
            time: 49.169,
            length: 0.254,
            cost: 109.937,
            begin_shape_index: 389,
            end_shape_index: 391,
            travel_mode: 'bicycle',
            travel_type: 'hybrid',
          },
          {
            type: 10,
            instruction: 'Turn right onto Straße 142.',
            verbal_transition_alert_instruction: 'Turn right onto Straße 142.',
            verbal_succinct_transition_instruction: 'Turn right.',
            verbal_pre_transition_instruction: 'Turn right onto Straße 142.',
            verbal_post_transition_instruction: 'Continue for 1 kilometer.',
            street_names: ['Straße 142'],
            bearing_before: 114,
            bearing_after: 202,
            time: 238.501,
            length: 1.203,
            cost: 419.536,
            begin_shape_index: 391,
            end_shape_index: 430,
            travel_mode: 'bicycle',
            travel_type: 'hybrid',
          },
          {
            type: 15,
            instruction: 'Turn left onto Niehofer Straße.',
            verbal_transition_alert_instruction:
              'Turn left onto Niehofer Straße.',
            verbal_succinct_transition_instruction:
              'Turn left. Then, in 40 meters, Turn right onto Seefelder Straße.',
            verbal_pre_transition_instruction:
              'Turn left onto Niehofer Straße. Then, in 40 meters, Turn right onto Seefelder Straße.',
            verbal_post_transition_instruction: 'Continue for 40 meters.',
            street_names: ['Niehofer Straße'],
            bearing_before: 191,
            bearing_after: 106,
            time: 9.389,
            length: 0.038,
            cost: 31.002,
            begin_shape_index: 430,
            end_shape_index: 433,
            verbal_multi_cue: true,
            travel_mode: 'bicycle',
            travel_type: 'hybrid',
          },
          {
            type: 10,
            instruction: 'Turn right onto Seefelder Straße.',
            verbal_transition_alert_instruction:
              'Turn right onto Seefelder Straße.',
            verbal_succinct_transition_instruction: 'Turn right.',
            verbal_pre_transition_instruction:
              'Turn right onto Seefelder Straße.',
            verbal_post_transition_instruction: 'Continue for 100 meters.',
            street_names: ['Seefelder Straße'],
            bearing_before: 108,
            bearing_after: 198,
            time: 36.064,
            length: 0.128,
            cost: 81.905,
            begin_shape_index: 433,
            end_shape_index: 446,
            travel_mode: 'bicycle',
            travel_type: 'hybrid',
          },
          {
            type: 16,
            instruction: 'Bear left onto the cycleway.',
            verbal_transition_alert_instruction: 'Bear left onto the cycleway.',
            verbal_succinct_transition_instruction:
              'Bear left. Then Turn right onto Konrad-Wolf-Straße.',
            verbal_pre_transition_instruction:
              'Bear left onto the cycleway. Then Turn right onto Konrad-Wolf-Straße.',
            verbal_post_transition_instruction: 'Continue for 30 meters.',
            bearing_before: 197,
            bearing_after: 184,
            time: 8.25,
            length: 0.025,
            cost: 20.244,
            begin_shape_index: 446,
            end_shape_index: 452,
            verbal_multi_cue: true,
            travel_mode: 'bicycle',
            travel_type: 'hybrid',
          },
          {
            type: 10,
            instruction: 'Turn right onto Konrad-Wolf-Straße.',
            verbal_transition_alert_instruction:
              'Turn right onto Konrad-Wolf-Straße.',
            verbal_succinct_transition_instruction: 'Turn right.',
            verbal_pre_transition_instruction:
              'Turn right onto Konrad-Wolf-Straße.',
            verbal_post_transition_instruction: 'Continue for 400 meters.',
            street_names: ['Konrad-Wolf-Straße'],
            bearing_before: 141,
            bearing_after: 229,
            time: 75.026,
            length: 0.41,
            cost: 170.491,
            begin_shape_index: 452,
            end_shape_index: 476,
            travel_mode: 'bicycle',
            travel_type: 'hybrid',
          },
          {
            type: 15,
            instruction: 'Turn left onto Bahnhofstraße.',
            verbal_transition_alert_instruction:
              'Turn left onto Bahnhofstraße.',
            verbal_succinct_transition_instruction: 'Turn left.',
            verbal_pre_transition_instruction: 'Turn left onto Bahnhofstraße.',
            verbal_post_transition_instruction: 'Continue for 600 meters.',
            street_names: ['Bahnhofstraße'],
            bearing_before: 229,
            bearing_after: 140,
            time: 163.234,
            length: 0.604,
            cost: 1345.086,
            begin_shape_index: 476,
            end_shape_index: 516,
            travel_mode: 'bicycle',
            travel_type: 'hybrid',
          },
          {
            type: 4,
            instruction: 'You have arrived at your destination.',
            verbal_transition_alert_instruction:
              'You will arrive at your destination.',
            verbal_pre_transition_instruction:
              'You have arrived at your destination.',
            bearing_before: 99,
            time: 0.0,
            length: 0.0,
            cost: 0.0,
            begin_shape_index: 516,
            end_shape_index: 516,
            travel_mode: 'bicycle',
            travel_type: 'hybrid',
          },
        ],
        summary: {
          has_time_restrictions: false,
          has_toll: false,
          has_highway: false,
          has_ferry: false,
          min_lat: 52.543372,
          min_lon: 13.496889,
          max_lat: 52.628583,
          max_lon: 13.527286,
          time: 2468.182,
          length: 12.027,
          cost: 6352.35,
        },
        shape:
          'g|akcBcvdwXY[aUeXuA{G}CcGwBiBwBiBgOuAwDsBLwv@Roh@uGgIwCsDaJaLkCeDqDqEa@c@sGeKcAmF|LcFxCoAnVoKvJgEjJaEf[yMpB{@|LgFhCqAjEuBdBu@rCuAfCeBrA{Bp@yAtAwDd@`@p@Tn@Pp@Ap@Wd@a@^o@Vq@Nw@JaA@eACcAc@aCXs@\\g@pR_X|OuThd@yn@vi@}u@pX_`@|HkKRYdE_GvAmBrAiBxCcEzQ}VrUq\\nQeWd^sf@zAsBvFwGj_@sd@ll@_v@`v@e`AnZa^xNsR`Wo`@lKeS~AwChHcPdEkJvCgGnGgK~FsHlIuG~@a@fH{ClG}B`h@yPdXyInWgGzUoD`TaDvFq@rZoD~eA{L~_BcVrjBiYpBYbc@yFrZcGhWkDzd@kFjPiBzCg@jDkA|GcDdL_FfKyGrVqP`JoG|FaErAaAvOaK|@q@bFkDlCgBjQuLdHqEfLyFjD{ApCgApD}AfVmJhBs@nDcArAUdCa@fDlA`BRV@nABdKZbQ\\dIMtAE|@GhPqEXGrPgEhPkDZGvFgA`AvE`AzE`AtEn@zCvCdNrCrNzB~KrAlH`@|BdKnl@Jh@t@zE`BfKl@vDjDm@VE`]uFnEu@hIuA`E}@xWeIlZ}DfJu@dBM`SqAzLwAzCWzSiAhOw@~Ai@lD~[N|AZzCbQ{FnJyDbAc@zH}CrFyB`CaA~CeAbIuCdGyBjTcIvAi@nJaEbNgFjDoB`GgH|PaWdLyPxOaVbXa`@bdAc|AbGaIdIyJfGkHbKoLpD}DzDyDhKyG`OCbA?vGAbJMhPq@zKStDf@|FzAhr@n]tdAhj@hAl@z@b@dmHvsDdy@db@rDpB~~@pe@hu@d]nB|@lZdNxbChfApPlHfDhAdKzDzHvC~B`A|I|D`n@hW|HdDvI`ApUjCjFl@xOrBrB^ZFb@NhDlAjXzLvFnCnHfDvXhMnAj@bGnCRH|FjApDy_@Hy@vB}P`AqEz@uDjCkIz@aC~@kCjAuC|Vqh@n@qAr@iA~@cAvA_AlCe@fIB^ArITvHG|Is@x_@cGzB]`LgBhL_B|Dw@tZyFtHsAnCOdGEnLPrLzApPnDnAVpLdC`B\\vJfBtHtA|Gn@|EPfEUjHm@~Cq@zB[~QcE|D}@VGf@IlAYb@|Df@fETpEShL?vARjM|@xJnCxUpHte@lCrHXjB~D|T`BnIZ~AB~AJnCv@rDh@hCt@`D|A~Br@lB`Orj@nDhQ~Wl~@X|@|B`IlAfEbCdGvAlDhDvLzCrApGdUbDbLbApD~FtSnFhRbHpVp@`Cn@|B~BnIvCbKzCnKzJp]bCdIbB|FrDfMtSft@zEbTvXheA`@zAfCfI|DbMtR`q@jJ`\\tIh[jIb[pJh^n@`CvGjWH\\xBjI^zAhAjE@Dl@xBT|@\\c@r@{@f@m@t@_ApCmDtDyEn@u@\\c@`@e@rCeDvAcBf@k@lC{C`AkAPSpXu[|DyEdMgOdF_ItAfExZr~@TdAN`BpAmA~@_AvCuEbAaA`A]~ABlCpAt@f@rCfB|@d@l@iDxw@upEzD~BhN`Ird@jXbe@`YvT`NvPzJbh@tZrc@pW~c@`Xfe@pXp@^frAtv@leA`o@|@l@^\\lBfBvAjCPTpGjJlBvCtFnIx@lA`HhKjG`Id@j@pFzGnEpFxIdJjHvHb@`@h@d@xQrPbTdOjEjCzBrA~@j@rDzBlO`HxEz@VaDNiAdDaYfBt@bNxGpCvAfJfFbHhDvJvETLRJ|BjA|@lBVh@TDvAZnBTfAWrAy@d@g@fA_BT]f@jAXn@Xn@`MzYvD`JhNn\\|BrFbB~DvBbFnErKr@`B`CzFdC|Fh@pAn[bu@`@fA|H`R|ArDrGpOlBpEvIpSjCjG~EvLnFfMR]fBmCRWpHaK`GqGbG_G`B{AxOuNfBaB~HiHxHmHd]s\\x@cAzAiBBC^c@tCaExB{CVe@@CfD_GfCqEl@cApCmGf@sAx@wB|BmGvCkInFkQNm@bF_TZ{ArB_KjAmH~BgQdBwQj@oJVeFJkBpJkvB',
      },
    ],
    summary: {
      has_time_restrictions: false,
      has_toll: false,
      has_highway: false,
      has_ferry: false,
      min_lat: 52.543372,
      min_lon: 13.496889,
      max_lat: 52.628583,
      max_lon: 13.527286,
      time: 2468.182,
      length: 12.027,
      cost: 6352.35,
    },
    status_message: 'Found route between points',
    status: 0,
    units: 'kilometers',
    language: 'en-US',
  },
  id: 'valhalla_directions',
} as const;
