import type { LucideIcon } from 'lucide-react';
import {
  ArrowUp,
  ArrowUpRight,
  ArrowUpLeft,
  ArrowRight,
  ArrowLeft,
  CornerUpRight,
  CornerUpLeft,
  CornerRightUp,
  CornerLeftUp,
  CircleDot,
  CircleArrowRight,
  CircleArrowLeft,
  Flag,
  Merge,
  Ship,
  Bus,
  Building,
  Footprints,
  Navigation,
} from 'lucide-react';

const maneuverIconMap: Record<number, LucideIcon> = {
  0: Navigation,
  1: CircleDot,
  2: CircleDot,
  3: CircleDot,
  4: Flag,
  5: Flag,
  6: Flag,
  7: ArrowUp,
  8: ArrowUp,
  9: ArrowUpRight,
  10: ArrowRight,
  11: CornerUpRight,
  12: CornerRightUp,
  13: CornerLeftUp,
  14: CornerUpLeft,
  15: ArrowLeft,
  16: ArrowUpLeft,
  17: ArrowUp,
  18: ArrowUpRight,
  19: ArrowUpLeft,
  20: CornerUpRight,
  21: CornerUpLeft,
  22: ArrowUp,
  23: ArrowUpRight,
  24: ArrowUpLeft,
  25: Merge,
  26: CircleArrowRight,
  27: CircleArrowLeft,
  28: Ship,
  29: Ship,
  30: Bus,
  31: Bus,
  32: Bus,
  33: Bus,
  34: Bus,
  35: Bus,
  36: Bus,
  37: Merge,
  38: Merge,
  39: Building,
  40: Footprints,
  41: Footprints,
  42: Building,
  43: Building,
};

export const getManeuverIcon = (type: number): LucideIcon => {
  return maneuverIconMap[type] ?? Navigation;
};
